### PR TITLE
Swiss cross background & option to skip output file name check

### PR DESCRIPTION
**Pull request by ChrisBuergi**
- QRBill: Set the fill color of the Swiss cross background explicitly
- CLI: Option to skip output file name check, so the output file name does not need to end with ".svg".

Thanks for this great utility!

### CODE REVIEW

**Comment by claudep** [comment]
Out of curiosity, what's the use case of skipping the extension control? We might also consider changing the error into a warning (without adding a new option).

**Comment by ChrisBuergi** [comment]
I have two Python envs where I call "qrbill" via a subprocess and use NamedTemporaryFile to capture the output. I was under the impression, that with NamedTemporaryFile it's not possible to create *.svg files, but I just learned that this is possible with the "suffix" argument. Sorry for my confusion.

So for me the check in the CLI now does not matter, but maybe it would still be nice to have that error converted to a warning for other cases.

**Comment by claudep** [comment]
I committed your first commit as is, and pushed c287ef717e8ca to change the error into warning. Thanks for your contribution.

**Comment by ChrisBuergi** [comment]
Ok, perfect. Thank you!

**Pull request closed without merging**
