### PR TITLE
Fixes #55 - Add a font_factor argument to bills

### LINKED ISSUE #55: Add a font factor parameter
In certain cases, the font sizes may be judged a bit too small or too large. Adding a font-factor parameter could allow the user to specify a custom scaling factor for fonts.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@AntonMezger Do you think this patch might help you?

**Comment by AntonMezger** [comment]
We are actually away, but we will see to it next week. Thanks a lot for your awesome work!

**Comment by AntonMezger** [comment]
Hi Claude,

tried it out and it works fine (I use 1.1 to increase slightly my fonts. Thanks a lot.

**Comment by AntonMezger** [comment]
Hi Claude,

 

Thank you for that feature; it works fine.

 

However I got from UBS again some remarks. On our payments, the QR code is 44 mm instead of 46 mm and the 5mm from borders were also not very exact. I ordered now special QR perforated paper in order to make the fine adjustments and I hope they will be happy then, but I think they are a little bit picky (pinailleur en fr)

 

Best regards

 

Anne-Chantal

 

De : Claude Paroz ***@***.***> 
Envoyé : samedi 24 avril 2021 16:47
À : claudep/swiss-qr-bill ***@***.***>
Cc : Anton Mezger ***@***.***>; Mention ***@***.***>
Objet : Re: [claudep/swiss-qr-bill] Fixes #55 - Add a font_factor argument to bills (#63)

 

@AntonMezger <https://github.com/AntonMezger>  Do you think this patch might help you?

**Pull request merged**
