### PR TITLE
Restructure qrbill

### PR DESCRIPTION
**Pull request by molitoris**
- bill contains business logic
- address stores information about creditor and debtor
- printer draws bill
- errors contain internally raised errors

bill
----
- Attributes stored as properties
- Made class more conform with QR bill specification
- Check for mandatory properties when save is called

address
-------
- Separate class
- Supports unstructured and structured address

printer
-------
- Base class 'Printer'
- Concrete implementation with SVGPrinter
- Divided drawing step into multiple subtasks
    - receipt part
    - payment part
    - paragraph
    - amount
    - title
    - qr code
    - swiss cross
    - blank field

testing
-------
- Split testing (qr_bill, address, printer)
- Simplify unit testing

Signed-off-by: Rafa Molitoris <rafa.molitoris@gmail.com>

### CODE REVIEW

**Comment by claudep** [comment]
Many thanks for your contribution! I will probably not merge your whole pull request as a block, as it contains many separate things. I'll examine it during the next days/weeks and will try to integrate bits of it (keeping you as author or co-author, of course).

**Comment by molitoris** [comment]
Hi Claude
It was a lot of fun for me to push the project forward. Contact me if there are any ambiguities or if you disagree with certain sections of the new implementation.

**Comment by claudep** [comment]
Rafa, I'm sorry but wasn't able to spend time on this lately. I think that instead of such a big patch, you should try to submit smaller chunks so we can discuss separately about your suggestions. This way, I may be more likely to find the time to handle things bit by bit.

**Comment by sbor23** [comment]
@molitoris I would suggest upstreaming the Renderer refactoring first. If you're ok with it I can also make a separate PR based on yours.

We need to write to PDF as a requirement, so this would make things a lot easier.

**Comment by molitoris** [comment]
@claudep I try to split the PR up. I will first look into separating the logic from the output generation.

**Comment by claudep** [comment]
Thanks. The smaller (but consistent) are the changes, the better. If there are design choices, please open a ticket to discuss it before spending too much time for something I may finally not accept.

**Comment by claudep** [comment]
Closing, feel free to reopen with smaller, more focused patches!

**Pull request closed without merging**
